name: Build and push to GCR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or your preferred version
      
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Angular App
      run: npm run build -- --prod
      
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker Image to GCR
      run: |
        echo "gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:latest" > .GCR_NAME
        docker build -t $(cat .GCR_NAME) .
        gcloud auth configure-docker
        docker push $(cat .GCR_NAME)

